language: java
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
script: mvn clean install
after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd target/site/en/ 
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='Travis CI' -c user.email='travis@dhis2.org' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://${GITHUB_TOKEN}@github.com/dhis2/dhis2-docs gh-pages &2>/dev/null
  fi
jdk:
- openjdk7
notifications:
  email:
  - jason.p.pickering@gmail.com
env:
  secure: j8o/CjjpUHW5maKuroMnxWCXHqEnIB/l6DpUzARBBXs3klQahmCidxqAMkqTG5sdgMuXT1bv8LXI2pbCy5ZUxD32S13bypL9M4IKvJsCq7xqrUNQJ/Kys/Pb8DXvpq8ZY6ER/Df32NsUDoiBohseEP6rLfe6JFlW1HvtNmtP/o8=
