---
language: java
# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script: mvn clean install
jdk:
- openjdk7
notifications:
  email:
  - jason.p.pickering@gmail.com
